# coding: utf-8

"""
    Twitter OpenAPI

    Twitter OpenAPI(Swagger) specification

    The version of the OpenAPI document: 0.0.1
    Contact: yuki@yuki0311.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import re  # noqa: F401
import io
import warnings

from pydantic import validate_arguments, ValidationError
from typing_extensions import Annotated

from pydantic import StrictBool, StrictInt, StrictStr


from twitter_openapi_python_generated.api_client import ApiClient
from twitter_openapi_python_generated.api_response import ApiResponse
from twitter_openapi_python_generated.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)


class V11GetApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_arguments
    def get_friends_following_list(self, include_profile_interstitial_type : StrictInt, include_blocking : StrictInt, include_blocked_by : StrictInt, include_followed_by : StrictInt, include_want_retweets : StrictInt, include_mute_edge : StrictInt, include_can_dm : StrictInt, include_can_media_tag : StrictInt, include_ext_has_nft_avatar : StrictInt, include_ext_is_blue_verified : StrictInt, include_ext_verified_type : StrictInt, include_ext_profile_image_shape : StrictInt, skip_status : StrictInt, cursor : StrictInt, user_id : StrictStr, count : StrictInt, with_total_count : StrictBool, **kwargs) -> None:  # noqa: E501
        """get_friends_following_list  # noqa: E501

        get friends following list  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_friends_following_list(include_profile_interstitial_type, include_blocking, include_blocked_by, include_followed_by, include_want_retweets, include_mute_edge, include_can_dm, include_can_media_tag, include_ext_has_nft_avatar, include_ext_is_blue_verified, include_ext_verified_type, include_ext_profile_image_shape, skip_status, cursor, user_id, count, with_total_count, async_req=True)
        >>> result = thread.get()

        :param include_profile_interstitial_type: (required)
        :type include_profile_interstitial_type: int
        :param include_blocking: (required)
        :type include_blocking: int
        :param include_blocked_by: (required)
        :type include_blocked_by: int
        :param include_followed_by: (required)
        :type include_followed_by: int
        :param include_want_retweets: (required)
        :type include_want_retweets: int
        :param include_mute_edge: (required)
        :type include_mute_edge: int
        :param include_can_dm: (required)
        :type include_can_dm: int
        :param include_can_media_tag: (required)
        :type include_can_media_tag: int
        :param include_ext_has_nft_avatar: (required)
        :type include_ext_has_nft_avatar: int
        :param include_ext_is_blue_verified: (required)
        :type include_ext_is_blue_verified: int
        :param include_ext_verified_type: (required)
        :type include_ext_verified_type: int
        :param include_ext_profile_image_shape: (required)
        :type include_ext_profile_image_shape: int
        :param skip_status: (required)
        :type skip_status: int
        :param cursor: (required)
        :type cursor: int
        :param user_id: (required)
        :type user_id: str
        :param count: (required)
        :type count: int
        :param with_total_count: (required)
        :type with_total_count: bool
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: None
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            raise ValueError("Error! Please call the get_friends_following_list_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data")
        return self.get_friends_following_list_with_http_info(include_profile_interstitial_type, include_blocking, include_blocked_by, include_followed_by, include_want_retweets, include_mute_edge, include_can_dm, include_can_media_tag, include_ext_has_nft_avatar, include_ext_is_blue_verified, include_ext_verified_type, include_ext_profile_image_shape, skip_status, cursor, user_id, count, with_total_count, **kwargs)  # noqa: E501

    @validate_arguments
    def get_friends_following_list_with_http_info(self, include_profile_interstitial_type : StrictInt, include_blocking : StrictInt, include_blocked_by : StrictInt, include_followed_by : StrictInt, include_want_retweets : StrictInt, include_mute_edge : StrictInt, include_can_dm : StrictInt, include_can_media_tag : StrictInt, include_ext_has_nft_avatar : StrictInt, include_ext_is_blue_verified : StrictInt, include_ext_verified_type : StrictInt, include_ext_profile_image_shape : StrictInt, skip_status : StrictInt, cursor : StrictInt, user_id : StrictStr, count : StrictInt, with_total_count : StrictBool, **kwargs) -> ApiResponse:  # noqa: E501
        """get_friends_following_list  # noqa: E501

        get friends following list  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_friends_following_list_with_http_info(include_profile_interstitial_type, include_blocking, include_blocked_by, include_followed_by, include_want_retweets, include_mute_edge, include_can_dm, include_can_media_tag, include_ext_has_nft_avatar, include_ext_is_blue_verified, include_ext_verified_type, include_ext_profile_image_shape, skip_status, cursor, user_id, count, with_total_count, async_req=True)
        >>> result = thread.get()

        :param include_profile_interstitial_type: (required)
        :type include_profile_interstitial_type: int
        :param include_blocking: (required)
        :type include_blocking: int
        :param include_blocked_by: (required)
        :type include_blocked_by: int
        :param include_followed_by: (required)
        :type include_followed_by: int
        :param include_want_retweets: (required)
        :type include_want_retweets: int
        :param include_mute_edge: (required)
        :type include_mute_edge: int
        :param include_can_dm: (required)
        :type include_can_dm: int
        :param include_can_media_tag: (required)
        :type include_can_media_tag: int
        :param include_ext_has_nft_avatar: (required)
        :type include_ext_has_nft_avatar: int
        :param include_ext_is_blue_verified: (required)
        :type include_ext_is_blue_verified: int
        :param include_ext_verified_type: (required)
        :type include_ext_verified_type: int
        :param include_ext_profile_image_shape: (required)
        :type include_ext_profile_image_shape: int
        :param skip_status: (required)
        :type skip_status: int
        :param cursor: (required)
        :type cursor: int
        :param user_id: (required)
        :type user_id: str
        :param count: (required)
        :type count: int
        :param with_total_count: (required)
        :type with_total_count: bool
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the 
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: None
        """

        _params = locals()

        _all_params = [
            'include_profile_interstitial_type',
            'include_blocking',
            'include_blocked_by',
            'include_followed_by',
            'include_want_retweets',
            'include_mute_edge',
            'include_can_dm',
            'include_can_media_tag',
            'include_ext_has_nft_avatar',
            'include_ext_is_blue_verified',
            'include_ext_verified_type',
            'include_ext_profile_image_shape',
            'skip_status',
            'cursor',
            'user_id',
            'count',
            'with_total_count'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_friends_following_list" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('include_profile_interstitial_type') is not None:  # noqa: E501
            _query_params.append(('include_profile_interstitial_type', _params['include_profile_interstitial_type']))

        if _params.get('include_blocking') is not None:  # noqa: E501
            _query_params.append(('include_blocking', _params['include_blocking']))

        if _params.get('include_blocked_by') is not None:  # noqa: E501
            _query_params.append(('include_blocked_by', _params['include_blocked_by']))

        if _params.get('include_followed_by') is not None:  # noqa: E501
            _query_params.append(('include_followed_by', _params['include_followed_by']))

        if _params.get('include_want_retweets') is not None:  # noqa: E501
            _query_params.append(('include_want_retweets', _params['include_want_retweets']))

        if _params.get('include_mute_edge') is not None:  # noqa: E501
            _query_params.append(('include_mute_edge', _params['include_mute_edge']))

        if _params.get('include_can_dm') is not None:  # noqa: E501
            _query_params.append(('include_can_dm', _params['include_can_dm']))

        if _params.get('include_can_media_tag') is not None:  # noqa: E501
            _query_params.append(('include_can_media_tag', _params['include_can_media_tag']))

        if _params.get('include_ext_has_nft_avatar') is not None:  # noqa: E501
            _query_params.append(('include_ext_has_nft_avatar', _params['include_ext_has_nft_avatar']))

        if _params.get('include_ext_is_blue_verified') is not None:  # noqa: E501
            _query_params.append(('include_ext_is_blue_verified', _params['include_ext_is_blue_verified']))

        if _params.get('include_ext_verified_type') is not None:  # noqa: E501
            _query_params.append(('include_ext_verified_type', _params['include_ext_verified_type']))

        if _params.get('include_ext_profile_image_shape') is not None:  # noqa: E501
            _query_params.append(('include_ext_profile_image_shape', _params['include_ext_profile_image_shape']))

        if _params.get('skip_status') is not None:  # noqa: E501
            _query_params.append(('skip_status', _params['skip_status']))

        if _params.get('cursor') is not None:  # noqa: E501
            _query_params.append(('cursor', _params['cursor']))

        if _params.get('user_id') is not None:  # noqa: E501
            _query_params.append(('user_id', _params['user_id']))

        if _params.get('count') is not None:  # noqa: E501
            _query_params.append(('count', _params['count']))

        if _params.get('with_total_count') is not None:  # noqa: E501
            _query_params.append(('with_total_count', _params['with_total_count']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # authentication setting
        _auth_settings = ['ClientLanguage', 'CookieCt0', 'ActiveUser', 'UserAgent', 'CookieAuthToken', 'AuthType', 'CsrfToken', 'GuestToken', 'BearerAuth']  # noqa: E501

        _response_types_map = {}

        return self.api_client.call_api(
            '/1.1/friends/following/list.json', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def get_search_typeahead(self, include_ext_is_blue_verified : StrictInt, include_ext_verified_type : StrictInt, include_ext_profile_image_shape : StrictInt, q : StrictStr, src : StrictStr, result_type : StrictStr, **kwargs) -> None:  # noqa: E501
        """get_search_typeahead  # noqa: E501

        get search typeahead  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_search_typeahead(include_ext_is_blue_verified, include_ext_verified_type, include_ext_profile_image_shape, q, src, result_type, async_req=True)
        >>> result = thread.get()

        :param include_ext_is_blue_verified: (required)
        :type include_ext_is_blue_verified: int
        :param include_ext_verified_type: (required)
        :type include_ext_verified_type: int
        :param include_ext_profile_image_shape: (required)
        :type include_ext_profile_image_shape: int
        :param q: (required)
        :type q: str
        :param src: (required)
        :type src: str
        :param result_type: (required)
        :type result_type: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: None
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            raise ValueError("Error! Please call the get_search_typeahead_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data")
        return self.get_search_typeahead_with_http_info(include_ext_is_blue_verified, include_ext_verified_type, include_ext_profile_image_shape, q, src, result_type, **kwargs)  # noqa: E501

    @validate_arguments
    def get_search_typeahead_with_http_info(self, include_ext_is_blue_verified : StrictInt, include_ext_verified_type : StrictInt, include_ext_profile_image_shape : StrictInt, q : StrictStr, src : StrictStr, result_type : StrictStr, **kwargs) -> ApiResponse:  # noqa: E501
        """get_search_typeahead  # noqa: E501

        get search typeahead  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_search_typeahead_with_http_info(include_ext_is_blue_verified, include_ext_verified_type, include_ext_profile_image_shape, q, src, result_type, async_req=True)
        >>> result = thread.get()

        :param include_ext_is_blue_verified: (required)
        :type include_ext_is_blue_verified: int
        :param include_ext_verified_type: (required)
        :type include_ext_verified_type: int
        :param include_ext_profile_image_shape: (required)
        :type include_ext_profile_image_shape: int
        :param q: (required)
        :type q: str
        :param src: (required)
        :type src: str
        :param result_type: (required)
        :type result_type: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the 
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: None
        """

        _params = locals()

        _all_params = [
            'include_ext_is_blue_verified',
            'include_ext_verified_type',
            'include_ext_profile_image_shape',
            'q',
            'src',
            'result_type'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_search_typeahead" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('include_ext_is_blue_verified') is not None:  # noqa: E501
            _query_params.append(('include_ext_is_blue_verified', _params['include_ext_is_blue_verified']))

        if _params.get('include_ext_verified_type') is not None:  # noqa: E501
            _query_params.append(('include_ext_verified_type', _params['include_ext_verified_type']))

        if _params.get('include_ext_profile_image_shape') is not None:  # noqa: E501
            _query_params.append(('include_ext_profile_image_shape', _params['include_ext_profile_image_shape']))

        if _params.get('q') is not None:  # noqa: E501
            _query_params.append(('q', _params['q']))

        if _params.get('src') is not None:  # noqa: E501
            _query_params.append(('src', _params['src']))

        if _params.get('result_type') is not None:  # noqa: E501
            _query_params.append(('result_type', _params['result_type']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # authentication setting
        _auth_settings = ['ClientLanguage', 'CookieCt0', 'ActiveUser', 'UserAgent', 'CookieAuthToken', 'AuthType', 'CsrfToken', 'GuestToken', 'BearerAuth']  # noqa: E501

        _response_types_map = {}

        return self.api_client.call_api(
            '/1.1/search/typeahead.json', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))
