# coding: utf-8

"""
    Twitter OpenAPI

    Twitter OpenAPI(Swagger) specification

    The version of the OpenAPI document: 0.0.1
    Contact: yuki@yuki0311.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ContentItemType(str, Enum):
    """
    ContentItemType
    """

    """
    allowed enum values
    """
    TIMELINETWEET = 'TimelineTweet'
    TIMELINETIMELINECURSOR = 'TimelineTimelineCursor'
    TIMELINEUSER = 'TimelineUser'
    TIMELINEPROMPT = 'TimelinePrompt'
    TIMELINEMESSAGEPROMPT = 'TimelineMessagePrompt'
    TIMELINECOMMUNITY = 'TimelineCommunity'
    TIMELINETOMBSTONE = 'TimelineTombstone'
    TIMELINETREND = 'TimelineTrend'
    TIMELINENOTIFICATION = 'TimelineNotification'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ContentItemType from a JSON string"""
        return cls(json.loads(json_str))


