# coding: utf-8

"""
    Twitter OpenAPI

    Twitter OpenAPI(Swagger) specification  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: yuki@yuki0311.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class ContentEntryType(str, Enum):
    """
    ContentEntryType
    """

    """
    allowed enum values
    """
    TIMELINETIMELINEITEM = 'TimelineTimelineItem'
    TIMELINETIMELINECURSOR = 'TimelineTimelineCursor'
    TIMELINETIMELINEMODULE = 'TimelineTimelineModule'

    @classmethod
    def from_json(cls, json_str: str) -> ContentEntryType:
        """Create an instance of ContentEntryType from a JSON string"""
        return ContentEntryType(json.loads(json_str))


