# coding: utf-8

"""
    Twitter OpenAPI

    Twitter OpenAPI(Swagger) specification

    The version of the OpenAPI document: 0.0.1
    Contact: yuki@yuki0311.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from twitter_openapi_python_generated.models.media_original_info_focus_rect import MediaOriginalInfoFocusRect
from typing import Optional, Set
from typing_extensions import Self

class MediaOriginalInfo(BaseModel):
    """
    MediaOriginalInfo
    """ # noqa: E501
    focus_rects: Optional[List[MediaOriginalInfoFocusRect]] = None
    height: StrictInt
    width: StrictInt
    __properties: ClassVar[List[str]] = ["focus_rects", "height", "width"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MediaOriginalInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in focus_rects (list)
        _items = []
        if self.focus_rects:
            for _item_focus_rects in self.focus_rects:
                if _item_focus_rects:
                    _items.append(_item_focus_rects.to_dict())
            _dict['focus_rects'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MediaOriginalInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "focus_rects": [MediaOriginalInfoFocusRect.from_dict(_item) for _item in obj["focus_rects"]] if obj.get("focus_rects") is not None else None,
            "height": obj.get("height"),
            "width": obj.get("width")
        })
        return _obj


