# coding: utf-8

"""
    Twitter OpenAPI

    Twitter OpenAPI(Swagger) specification

    The version of the OpenAPI document: 0.0.1
    Contact: yuki@yuki0311.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from twitter_openapi_python_generated.models.user_professional_category import UserProfessionalCategory
from typing import Optional, Set
from typing_extensions import Self

class UserProfessional(BaseModel):
    """
    UserProfessional
    """ # noqa: E501
    category: List[UserProfessionalCategory]
    professional_type: StrictStr
    rest_id: Annotated[str, Field(strict=True)]
    __properties: ClassVar[List[str]] = ["category", "professional_type", "rest_id"]

    @field_validator('professional_type')
    def professional_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['Business', 'Creator']):
            raise ValueError("must be one of enum values ('Business', 'Creator')")
        return value

    @field_validator('rest_id')
    def rest_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[0-9]+$", value):
            raise ValueError(r"must validate the regular expression /^[0-9]+$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserProfessional from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in category (list)
        _items = []
        if self.category:
            for _item_category in self.category:
                if _item_category:
                    _items.append(_item_category.to_dict())
            _dict['category'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserProfessional from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "category": [UserProfessionalCategory.from_dict(_item) for _item in obj["category"]] if obj.get("category") is not None else None,
            "professional_type": obj.get("professional_type"),
            "rest_id": obj.get("rest_id")
        })
        return _obj


