# coding: utf-8

"""
    Twitter OpenAPI

    Twitter OpenAPI(Swagger) specification

    The version of the OpenAPI document: 0.0.1
    Contact: yuki@yuki0311.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twitter_openapi_python_generated.models.tweet_edit_control import TweetEditControl

class TestTweetEditControl(unittest.TestCase):
    """TweetEditControl unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TweetEditControl:
        """Test TweetEditControl
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TweetEditControl`
        """
        model = TweetEditControl()
        if include_optional:
            return TweetEditControl(
                edit_control_initial = twitter_openapi_python_generated.models.tweet_edit_control_initial.TweetEditControlInitial(
                    edit_tweet_ids = [
                        '4'
                        ], 
                    editable_until_msecs = '4', 
                    edits_remaining = '4', 
                    is_edit_eligible = True, ),
                edit_tweet_ids = [
                    '4'
                    ],
                editable_until_msecs = '4',
                edits_remaining = '4',
                initial_tweet_id = '4',
                is_edit_eligible = True
            )
        else:
            return TweetEditControl(
        )
        """

    def testTweetEditControl(self):
        """Test TweetEditControl"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
