# coding: utf-8

"""
    Twitter OpenAPI

    Twitter OpenAPI(Swagger) specification

    The version of the OpenAPI document: 0.0.1
    Contact: yuki@yuki0311.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twitter_openapi_python_generated.models.ranked_community_tweet_data import RankedCommunityTweetData

class TestRankedCommunityTweetData(unittest.TestCase):
    """RankedCommunityTweetData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RankedCommunityTweetData:
        """Test RankedCommunityTweetData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RankedCommunityTweetData`
        """
        model = RankedCommunityTweetData()
        if include_optional:
            return RankedCommunityTweetData(
                community_results = twitter_openapi_python_generated.models.ranked_community_results.RankedCommunityResults(
                    result = twitter_openapi_python_generated.models.ranked_community_result.RankedCommunityResult(
                        __typename = 'TimelineTweet', 
                        ranked_community_timeline = twitter_openapi_python_generated.models.timeline_result.TimelineResult(
                            id = '', 
                            timeline = twitter_openapi_python_generated.models.timeline.Timeline(
                                instructions = [
                                    null
                                    ], 
                                metadata = { }, 
                                response_objects = { }, ), ), ), )
            )
        else:
            return RankedCommunityTweetData(
                community_results = twitter_openapi_python_generated.models.ranked_community_results.RankedCommunityResults(
                    result = twitter_openapi_python_generated.models.ranked_community_result.RankedCommunityResult(
                        __typename = 'TimelineTweet', 
                        ranked_community_timeline = twitter_openapi_python_generated.models.timeline_result.TimelineResult(
                            id = '', 
                            timeline = twitter_openapi_python_generated.models.timeline.Timeline(
                                instructions = [
                                    null
                                    ], 
                                metadata = { }, 
                                response_objects = { }, ), ), ), ),
        )
        """

    def testRankedCommunityTweetData(self):
        """Test RankedCommunityTweetData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
