# coding: utf-8

"""
    Twitter OpenAPI

    Twitter OpenAPI(Swagger) specification

    The version of the OpenAPI document: 0.0.1
    Contact: yuki@yuki0311.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twitter_openapi_python_generated.models.tweet_card_legacy_binding_value_data_image import TweetCardLegacyBindingValueDataImage

class TestTweetCardLegacyBindingValueDataImage(unittest.TestCase):
    """TweetCardLegacyBindingValueDataImage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TweetCardLegacyBindingValueDataImage:
        """Test TweetCardLegacyBindingValueDataImage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TweetCardLegacyBindingValueDataImage`
        """
        model = TweetCardLegacyBindingValueDataImage()
        if include_optional:
            return TweetCardLegacyBindingValueDataImage(
                alt = '',
                height = 56,
                url = '',
                width = 56
            )
        else:
            return TweetCardLegacyBindingValueDataImage(
                height = 56,
                url = '',
                width = 56,
        )
        """

    def testTweetCardLegacyBindingValueDataImage(self):
        """Test TweetCardLegacyBindingValueDataImage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
