# coding: utf-8

"""
    Twitter OpenAPI

    Twitter OpenAPI(Swagger) specification

    The version of the OpenAPI document: 0.0.1
    Contact: yuki@yuki0311.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twitter_openapi_python_generated.models.url import Url

class TestUrl(unittest.TestCase):
    """Url unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Url:
        """Test Url
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Url`
        """
        model = Url()
        if include_optional:
            return Url(
                display_url = '',
                expanded_url = '',
                indices = [
                    56
                    ],
                url = ''
            )
        else:
            return Url(
                display_url = '',
                indices = [
                    56
                    ],
                url = '',
        )
        """

    def testUrl(self):
        """Test Url"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
