# coding: utf-8

"""
    Twitter OpenAPI

    Twitter OpenAPI(Swagger) specification  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: yuki@yuki0311.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import twitter_openapi_python_generated
from twitter_openapi_python_generated.models.timeline_add_entries import TimelineAddEntries  # noqa: E501
from twitter_openapi_python_generated.rest import ApiException

class TestTimelineAddEntries(unittest.TestCase):
    """TimelineAddEntries unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TimelineAddEntries
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TimelineAddEntries`
        """
        model = twitter_openapi_python_generated.models.timeline_add_entries.TimelineAddEntries()  # noqa: E501
        if include_optional :
            return TimelineAddEntries(
                entries = [
                    twitter_openapi_python_generated.models.timeline_add_entry.TimelineAddEntry(
                        content = null, 
                        entry_id = '25375e030fccba00917317c574773100bf03b5f', 
                        sort_index = '4', )
                    ], 
                type = 'TimelineAddEntries'
            )
        else :
            return TimelineAddEntries(
                entries = [
                    twitter_openapi_python_generated.models.timeline_add_entry.TimelineAddEntry(
                        content = null, 
                        entry_id = '25375e030fccba00917317c574773100bf03b5f', 
                        sort_index = '4', )
                    ],
                type = 'TimelineAddEntries',
        )
        """

    def testTimelineAddEntries(self):
        """Test TimelineAddEntries"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
