# coding: utf-8

"""
    Twitter OpenAPI

    Twitter OpenAPI(Swagger) specification

    The version of the OpenAPI document: 0.0.1
    Contact: yuki@yuki0311.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import twitter_openapi_python_generated
from twitter_openapi_python_generated.api.v11_get_api import V11GetApi  # noqa: E501
from twitter_openapi_python_generated.rest import ApiException


class TestV11GetApi(unittest.TestCase):
    """V11GetApi unit test stubs"""

    def setUp(self):
        self.api = twitter_openapi_python_generated.api.v11_get_api.V11GetApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_friends_following_list(self):
        """Test case for get_friends_following_list

        """
        pass

    def test_get_search_typeahead(self):
        """Test case for get_search_typeahead

        """
        pass


if __name__ == '__main__':
    unittest.main()
