# coding: utf-8

"""
    Twitter OpenAPI

    Twitter OpenAPI(Swagger) specification

    The version of the OpenAPI document: 0.0.1
    Contact: yuki@yuki0311.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twitter_openapi_python_generated.api.user_api import UserApi


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserApi()

    def tearDown(self) -> None:
        pass

    def test_get_user_by_rest_id(self) -> None:
        """Test case for get_user_by_rest_id

        """
        pass

    def test_get_user_by_screen_name(self) -> None:
        """Test case for get_user_by_screen_name

        """
        pass


if __name__ == '__main__':
    unittest.main()
