# coding: utf-8

"""
    Twitter OpenAPI

    Twitter OpenAPI(Swagger) specification  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: yuki@yuki0311.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import twitter_openapi_python_generated
from twitter_openapi_python_generated.api.default_api import DefaultApi  # noqa: E501
from twitter_openapi_python_generated.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = twitter_openapi_python_generated.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_profile_spotlights_query(self):
        """Test case for get_profile_spotlights_query

        """
        pass


if __name__ == '__main__':
    unittest.main()
