# coding: utf-8

"""
    Twitter OpenAPI

    Twitter OpenAPI(Swagger) specification  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: yuki@yuki0311.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import twitter_openapi_python_generated
from twitter_openapi_python_generated.api.users_api import UsersApi  # noqa: E501
from twitter_openapi_python_generated.rest import ApiException


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = twitter_openapi_python_generated.api.users_api.UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_users_by_rest_ids(self):
        """Test case for get_users_by_rest_ids

        """
        pass


if __name__ == '__main__':
    unittest.main()
