# coding: utf-8

"""
    Twitter OpenAPI

    Twitter OpenAPI(Swagger) specification  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: yuki@yuki0311.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import twitter_openapi_python_generated
from twitter_openapi_python_generated.models.timeline_pin_entry import TimelinePinEntry  # noqa: E501
from twitter_openapi_python_generated.rest import ApiException

class TestTimelinePinEntry(unittest.TestCase):
    """TimelinePinEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TimelinePinEntry
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TimelinePinEntry`
        """
        model = twitter_openapi_python_generated.models.timeline_pin_entry.TimelinePinEntry()  # noqa: E501
        if include_optional :
            return TimelinePinEntry(
                entry = twitter_openapi_python_generated.models.timeline_add_entry.TimelineAddEntry(
                    content = null, 
                    entry_id = 'q072888001528021798096225500850762068629', 
                    sort_index = '4', ), 
                type = 'TimelineAddEntries'
            )
        else :
            return TimelinePinEntry(
                entry = twitter_openapi_python_generated.models.timeline_add_entry.TimelineAddEntry(
                    content = null, 
                    entry_id = 'q072888001528021798096225500850762068629', 
                    sort_index = '4', ),
                type = 'TimelineAddEntries',
        )
        """

    def testTimelinePinEntry(self):
        """Test TimelinePinEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
