# coding: utf-8

"""
    Twitter OpenAPI

    Twitter OpenAPI(Swagger) specification

    The version of the OpenAPI document: 0.0.1
    Contact: yuki@yuki0311.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twitter_openapi_python_generated.api.other_api import OtherApi


class TestOtherApi(unittest.TestCase):
    """OtherApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OtherApi()

    def tearDown(self) -> None:
        pass

    def test_other(self) -> None:
        """Test case for other

        """
        pass


if __name__ == '__main__':
    unittest.main()
